macro_rules! builtin_tool_entries {
    ($macro:ident $(, $arg:expr)* $(,)?) => {
        $macro! {
            $($arg,)*
            ("browser-open", BrowserOpen, browser_open),
            ("browser-list", Strings, browser_list),
            ("page-goto", Strings, browser_goto),
            ("page-back", Strings, browser_back),
            ("page-forward", Strings, browser_forward),
            ("page-reload", Strings, browser_reload),
            ("element-click", Strings, browser_click),
            ("element-double-click", Strings, browser_double_click),
            ("element-right-click", Strings, browser_right_click),
            ("element-type", Strings, browser_type),
            ("element-fill", Strings, browser_fill),
            ("keyboard-press", Strings, browser_press),
            ("keyboard-type", Strings, browser_keyboard_type),
            ("keyboard-down", Strings, browser_keyboard_down),
            ("keyboard-up", Strings, browser_keyboard_up),
            ("element-select", Strings, browser_select),
            ("element-check", Strings, browser_check),
            ("element-uncheck", Strings, browser_uncheck),
            ("time-sleep", Number { label: "ms" }, browser_wait_timeout),
            ("js-wait", Strings, browser_wait_function),
            ("element-exists", Strings, browser_exists),
            ("element-hover", Strings, browser_hover),
            ("element-upload", Strings, browser_upload),
            ("element-drag", Strings, browser_drag),
            ("page-snapshot", Strings, browser_page_snapshot),
            ("page-screenshot", Strings, browser_screenshot),
            ("element-screenshot", Strings, browser_element_screenshot),
            ("page-pdf", Strings, browser_pdf),
            ("js-eval", Strings, browser_eval),
            ("page-wait-navigation", Strings, browser_wait_navigation),
            ("page-scroll-to", XyNumbers, browser_scroll_to),
            ("page-scroll-by", XyNumbers, browser_scroll_by),
            ("browser-resize", XyNumbers, browser_resize),
            ("tab-list", Strings, tab_list),
            ("tab-new", Strings, tab_new),
            ("tab-select", Strings, tab_select),
            ("tab-close", Strings, tab_close),
            ("browser-version", Strings, browser_version),
            ("performance-metrics", Strings, browser_performance_metrics),
            ("network-log", Strings, browser_network_log),
            ("dialog-accept", Strings, browser_dialog_accept),
            ("dialog-dismiss", Strings, browser_dialog_dismiss),
            ("console", Strings, browser_console),
            ("console-clear", Strings, browser_console_clear),
            ("inspect-info", Strings, browser_inspect_info),
            ("inspect-highlight", Strings, browser_inspect_highlight),
            ("inspect-hide-highlight", Strings, browser_inspect_hide_highlight),
            ("inspect-pick", Number { label: "timeout-ms" }, browser_inspect_pick),
            ("tracing-start", Strings, browser_tracing_start),
            ("tracing-stop", Strings, browser_tracing_stop),
            ("mouse-move", XyNumbers, browser_mouse_move),
            ("mouse-click", XyNumbers, browser_mouse_click),
            ("mouse-down", MouseDownUp, browser_mouse_down),
            ("mouse-up", MouseDownUp, browser_mouse_up),
            ("mouse-wheel", MouseWheel, browser_mouse_wheel),
            ("touch-tap", XyNumbers, browser_touch_tap),
            ("cdp-call", Strings, browser_cdp),
            ("browser-close", Strings, browser_close),
        }
    };
}

pub(crate) use builtin_tool_entries;
